### ISSUE TITLE
Two failing MC files

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lst-sim-config#76]
Hi @Voutsi 
These two simtel files are failing when running lstchain on them:

```
File: /fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_58.286_az_32.748_/output_v1.4/simtel_corsika_theta_58.286_az_32.748_run62.simtel.gz 

/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_3476/sim_telarray/node_corsika_theta_41.666_az_291.198_/output_v1.4/simtel_corsika_theta_41.666_az_291.198_run252.simtel.gz
```

Command run:
```
lstchain_mc_r0_to_dl1 --input-file=/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_3476/sim_telarray/node_corsika_theta_41.666_az_291.198_/output_v1.4/simtel_corsika_theta_41.666_az_291.198_run252.simtel.gz --output-dir=/fefs/aswg/data/mc/DL1/AllSky/20240909_allsky_nsb_tuning_0.00/TrainingDataset/Protons/dec_3476/node_corsika_theta_41.666_az_291.198_ --config=/fefs/aswg/workspace/lstmcpipe/lstmcpipe/production_configs/20240909_v0.10.12_allsky_nsb_grid/NSB-0.00/lstchain_config_nsb0.00.json
```

Failing reason:
```
EOFError reading from "/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_3476/sim_telarray/node_corsika_theta_41.666_az_291.198_/output_v1.4/simtel_corsika_theta_41.666_az_291.198_run252.simtel.gz". Might be truncated
```

Could you please remove or reproduce them?

Thanks

**Comment by Voutsi** [comment]
Hi @vuillaut 

I removed the files now as a fast solution. I will try to reproduce them and add them back if everything is ok

**Comment by vuillaut** [comment]
Hi @Voutsi 

Here is a complete list of corrupted files (the first two are included here):

```
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_4822/sim_telarray/node_corsika_theta_29.249_az_319.533_/output_v1.4/simtel_corsika_theta_29.249_az_319.533_run158.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run36.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_31.575_/output_v1.4/simtel_corsika_theta_49.374_az_31.575_run129.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run18.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_53.795_az_32.599_/output_v1.4/simtel_corsika_theta_53.795_az_32.599_run115.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_58.286_az_32.748_/output_v1.4/simtel_corsika_theta_58.286_az_32.748_run62.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_45.843_az_338.112_/output_v1.4/simtel_corsika_theta_45.843_az_338.112_run65.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run209.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run157.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run94.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_335.678_/output_v1.4/simtel_corsika_theta_49.111_az_335.678_run187.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_335.678_/output_v1.4/simtel_corsika_theta_49.111_az_335.678_run112.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_335.678_/output_v1.4/simtel_corsika_theta_49.111_az_335.678_run136.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_335.678_/output_v1.4/simtel_corsika_theta_49.111_az_335.678_run23.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_931/sim_telarray/node_corsika_theta_50.032_az_257.329_/output_v1.4/simtel_corsika_theta_50.032_az_257.329_run32.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_931/sim_telarray/node_corsika_theta_56.566_az_98.125_/output_v1.4/simtel_corsika_theta_56.566_az_98.125_run120.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_931/sim_telarray/node_corsika_theta_69.809_az_269.697_/output_v1.4/simtel_corsika_theta_69.809_az_269.697_run71.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_931/sim_telarray/node_corsika_theta_69.809_az_90.303_/output_v1.4/simtel_corsika_theta_69.809_az_90.303_run65.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_min_1802/sim_telarray/node_corsika_theta_49.562_az_201.348_/output_v1.4/simtel_corsika_theta_49.562_az_201.348_run18.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_3476/sim_telarray/node_corsika_theta_41.666_az_291.198_/output_v1.4/simtel_corsika_theta_41.666_az_291.198_run252.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_29.249_az_40.467_/output_v1.4/simtel_corsika_theta_29.249_az_40.467_run398.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_29.249_az_40.467_/output_v1.4/simtel_corsika_theta_29.249_az_40.467_run107.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_41.026_az_48.313_/output_v1.4/simtel_corsika_theta_41.026_az_48.313_run238.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_41.026_az_48.313_/output_v1.4/simtel_corsika_theta_41.026_az_48.313_run192.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_310.704_/output_v1.4/simtel_corsika_theta_53.598_az_310.704_run255.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run11.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run311.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run249.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run81.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run262.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run68.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run198.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_53.598_az_49.296_/output_v1.4/simtel_corsika_theta_53.598_az_49.296_run356.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run118.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run186.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run143.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run386.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run136.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run62.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run394.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run196.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_311.676_/output_v1.4/simtel_corsika_theta_59.854_az_311.676_run270.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_48.324_/output_v1.4/simtel_corsika_theta_59.854_az_48.324_run151.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_48.324_/output_v1.4/simtel_corsika_theta_59.854_az_48.324_run70.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_48.324_/output_v1.4/simtel_corsika_theta_59.854_az_48.324_run293.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_59.854_az_48.324_/output_v1.4/simtel_corsika_theta_59.854_az_48.324_run120.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_65.98_az_313.368_/output_v1.4/simtel_corsika_theta_65.98_az_313.368_run19.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_65.98_az_313.368_/output_v1.4/simtel_corsika_theta_65.98_az_313.368_run86.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_4822/sim_telarray/node_corsika_theta_65.98_az_313.368_/output_v1.4/simtel_corsika_theta_65.98_az_313.368_run391.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_931/sim_telarray/node_corsika_theta_31.589_az_237.286_/output_v1.4/simtel_corsika_theta_31.589_az_237.286_run97.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_931/sim_telarray/node_corsika_theta_37.428_az_245.565_/output_v1.4/simtel_corsika_theta_37.428_az_245.565_run98.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/Protons/dec_931/sim_telarray/node_corsika_theta_37.428_az_245.565_/output_v1.4/simtel_corsika_theta_37.428_az_245.565_run226.simtel.gz

/fefs/aswg/data/mc/DL0/LSTProd2/TestDataset/sim_telarray/node_theta_52.374_az_301.217_/output_v1.4/simtel_corsika_theta_52.374_az_301.217_run158.simtel.gz
```

**Comment by Voutsi** [comment]
Thank you for the feedback.

**Comment by vuillaut** [comment]
Hi @Voutsi 

There is something very weird happening here. I now have errors on files that did not fail previously:

```
lstchain_mc_r0_to_dl1 -f /fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run109.simtel.gz -o . -c /fefs/aswg/workspace/lstmcpipe/lstmcpipe/production_configs/20240918_v0.10.12_allsky_nsb_grid/NSB-0.07/lstchain_config_nsb0.07.json
Found duplicated column obs_id, skipping
Found duplicated column event_id, skipping
EOFError reading from "/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run109.simtel.gz". Might be truncated
/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/ctapipe/io/simteleventsource.py:711: UserWarning: EOFError reading from "/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run109.simtel.gz". Might be truncated
  warnings.warn(msg)
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/bin/lstchain_mc_r0_to_dl1", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 74, in main
    r0_to_dl1.r0_to_dl1(
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/reco/r0_to_dl1.py", line 795, in r0_to_dl1
    write_simtel_energy_histogram(source, output_filename, obs_id=event.index.obs_id,
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/io/io.py", line 480, in write_simtel_energy_histogram
    for hist in source.file_.histograms:
TypeError: 'NoneType' object is not iterable
```

My first thought was that a bug from the processing script is affecting the files, but as you are the file owner, I fail to see how this could happen.

Any idea?

**Comment by maxnoe** [comment]
Hi,

The histograms are the very last thing that is written, so I assume this is a file where the process crashed and that at a "nice" part of writing the file so that all events it managed to write are intact.

**Comment by maxnoe** [comment]
Ah, sorry, nevermind. I didn't read the part about "worked before"

**Comment by Voutsi** [comment]
Hi @vuillaut 
it is indeed corrupted, missing few events. Weird that it didn't fail before. 
I think I need to implement some robust simtel checking tool like they have in prod6.
In any case I have resubmitted it. Should be ready by the morning.

**Comment by vuillaut** [comment]
Here is the list of failing files for the latest production I run:

GammaDiffuse:
```
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run109.simtel.gz 
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_335.678_/output_v1.4/simtel_corsika_theta_49.111_az_335.678_run157.simtel.gz
```

And Gamma:
```
/fefs/aswg/data/mc/DL0/LSTProd2/TestDataset/sim_telarray/node_theta_52.374_az_301.217_/output_v1.4/simtel_corsika_theta_52.374_az_301.217_run158.simtel.gz
```

**Comment by vuillaut** [comment]
Hello
Getting these errors again, on new files:
```
lstchain_mc_r0_to_dl1 -f /fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz -c /fefs/aswg/data/mc/DL1/AllSky/20240918_v0.10.12_allsky_nsb_tuning_0.14/TrainingDataset/GammaDiffuse/dec_6676/node_corsika_theta_49.111_az_24.322_/job_logs_r0dl1/lstchain_config_nsb0.14.json -o .
Found duplicated column obs_id, skipping
Found duplicated column event_id, skipping
EOFError reading from "/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz". Might be truncated
/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/ctapipe/io/simteleventsource.py:711: UserWarning: EOFError reading from "/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz". Might be truncated
  warnings.warn(msg)
Traceback (most recent call last):
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/bin/lstchain_mc_r0_to_dl1", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/scripts/lstchain_mc_r0_to_dl1.py", line 74, in main
    r0_to_dl1.r0_to_dl1(
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/reco/r0_to_dl1.py", line 795, in r0_to_dl1
    write_simtel_energy_histogram(source, output_filename, obs_id=event.index.obs_id,
  File "/fefs/aswg/software/conda/envs/lstchain-v0.10.12/lib/python3.11/site-packages/lstchain/io/io.py", line 480, in write_simtel_energy_histogram
    for hist in source.file_.histograms:
TypeError: 'NoneType' object is not iterable
```

@maxnoe is it possible that the simtel files get corrupted when being analyzed if the job fails for any reason?

**Comment by vuillaut** [comment]
@Voutsi I have these two files failing
```
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6166/sim_telarray/node_corsika_theta_49.374_az_328.425_/output_v1.4/simtel_corsika_theta_49.374_az_328.425_run109.simtel.gz
```

**Comment by Voutsi** [comment]
Hi @vuillaut 
the files were removed. I will try to reproduce them

**Comment by maxnoe** [comment]
>  is it possible that the simtel files get corrupted 

Not really, files are only opened in read only mode

**Comment by Voutsi** [comment]
Hi @vuillaut 
do you think that moving to a newer simtel version would create issues to lstmcpipe processing?
Sometimes (quite rarely) I see that simtel jobs are failing without an obvious to me reason. Like with the file:
/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/dec_6676/sim_telarray/node_corsika_theta_49.111_az_24.322_/output_v1.4/simtel_corsika_theta_49.111_az_24.322_run120.simtel.gz

So I would like to try a newer simtel installation. Would that be ok?

**Comment by jsitarek** [comment]
Hi @Voutsi ,
the safest thing would be to generate a single file with the newer version and check if this can be processed by lstchain_mc and by MCP

**Comment by vuillaut** [comment]
Hi @Voutsi,
All the files from `LSTProd2` can now be reduced to DL1 without issue.
I am closing this issue.

**Comment by vuillaut** [comment]
> Hi @Voutsi , the safest thing would be to generate a single file with the newer version and check if this can be processed by lstchain_mc and by MCP

The best thing would actually to test the files when they are generated, or raise issues and reprocess the files when failure happens during simtel generation.
